/*
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.Server;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerApi
 */
@Ignore
public class ServerApiTest {

    private final ServerApi api = new ServerApi();

    
    /**
     * List of servers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverGetTest() throws ApiException {
        InlineResponse200 response = api.serverGet();

        // TODO: test validations
    }
    
    /**
     * Create server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverPostTest() throws ApiException {
        Server server = null;
        InlineResponse2001 response = api.serverPost(server);

        // TODO: test validations
    }
    
    /**
     * Delete server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverServerIdDeleteTest() throws ApiException {
        UUID serverId = null;
        api.serverServerIdDelete(serverId);

        // TODO: test validations
    }
    
    /**
     * Server details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverServerIdGetTest() throws ApiException {
        UUID serverId = null;
        InlineResponse2001 response = api.serverServerIdGet(serverId);

        // TODO: test validations
    }
    
    /**
     * Modify server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverServerIdPutTest() throws ApiException {
        UUID serverId = null;
        Server server = null;
        InlineResponse2001 response = api.serverServerIdPut(serverId, server);

        // TODO: test validations
    }
    
}
